### ISSUE TITLE
Video call hangup crash on iOS 13

### ISSUE THREAD

**Issue by antonz0319** [sinch/docs#57] opened 2020-04-20 19:17 UTC
Hi, I am using Sinch SDK for voice/video call in my iOS app. 
Voice call is working well but video call is getting crash when hang up.  (In my case, app to app call)

Here are the steps to reproduce crash issue.
1. User A make a video call to User B
2. Wait until callDidProgress and hangup.
3. User A make a voice call to User B
4. Wait until callDidProgress and hangup.
Repeat 1,2,3,4. You will get crash in 2~3 repeats.

```
Here are the Xcode log.
[A1CE5A22-C584-4BA2-862C-860007903623] callDidEnd 6
2020-04-20 22:03:23.748587+0300 MyAppName[12278:2877024] *** Assertion failure in -[FBSSerialQueue assertOnQueue], /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/FrontBoardServices/FrontBoard-626.7/FrontBoardServices/FBSSerialQueue.m:98
2020-04-20 22:03:23.763771+0300 MyAppName[12278:2877024] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'threading violation: expected the main thread'
*** First throw call stack:
(0x1b47915f0 0x1b44b3bcc 0x1b46947bc 0x1b4acbd1c 0x1b9953a74 0x1b9909978 0x1b9909bd8 0x1b9909ae8 0x1b83b51e8 0x1b84ac22c 0x1b84acee4 0x10143856c 0x102bfe338 0x102bff730 0x102c06740 0x102c072e0 0x102c126c4 0x1b44a8b74 0x1b44ab740)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
*** 
```

<img width="617" alt="image" src="https://user-images.githubusercontent.com/34143928/79790426-5e408680-8354-11ea-9b4d-a9a2c9be5fde.png">

Next one is crashlytics log.
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/34143928/79791178-8da3c300-8355-11ea-9d06-e7d24be1d111.png">

Seem all webrtc based frameworks should be updated for iOS13. I can see many topics about this crash from google. 

I can support your team to reproduce crash if needed. Hope this issue can be fixed in next release or so. 

Thanks

**Comment by antonz0319** [comment] 2020-04-20 20:25
Please refer this link.
https://bugs.chromium.org/p/webrtc/issues/detail?id=11216&q=ios13&can=2

**Comment by christoffer-a-sinch** [comment] 2020-05-26 17:39
@antonz0319 Thanks for reporting this. The issue has been resolved in Sinch RTC iOS SDK 4.2.5, please see https://developers.sinch.com/docs/release-notes-voice-ios-sdk# (_"Fix crash in iOS 13 caused by method endGeneratingDeviceOrientationNotifications in WebRTC."_)

**Closed by christoffer-a-sinch** 2020-05-26 17:39 UTC

**Comment by antonz0319** [comment] 2020-05-26 17:42
Hi @christoffer-a-sinch , Yes, I've confirmed this issue with 4.2.5. It's working perfectly fine now. Thank you very much for your update!

**Comment by lalitalphonic** [comment] 2020-08-26 16:36
Hii i am getting an issue with sinch sdk my video call is working perfect but my voice is not receiving video is receiving perfectly don't know what is the issue can anyone help me out

**Comment by christoffer-a-sinch** [comment] 2020-08-26 20:26
@lalitalphonic can you please file a support ticket via https://www.sinch.com/customer-service/ (support@sinch.com) with some more details on what version of the Sinch SDK you are using, if possible please clearly describe the steps to reproduce the issue, and please attach application logs (including Sinch SDK logging). Thank you!
